apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport
  namespace: vijay-streaming
spec:
  type: NodePort
  selector:
    app: backend-streaming
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30010
    

