apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-env
  namespace: vijay-streaming
data:
  REACT_APP_AUTH_API_URL: "http://3.75.202.82:30010/api"
  REACT_APP_STREAMING_API_URL:  "http://3.75.202.82:30020/api"
  REACT_APP_STREAMING_PUBLIC_URL:  "http://3.75.202.82:30020"
  REACT_APP_ADMIN_API_URL:  "http://3.75.202.82:30030/api"
  REACT_APP_CHAT_API_URL:  "http://3.75.202.82:30040/api"
  REACT_APP_CHAT_SOCKET_URL:  "http://3.75.202.82:30040"

