apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-streaming
  namespace: vijay-streaming
  labels:
    app: frontend-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-streaming
  template:
    metadata:
      labels:
        app: frontend-streaming
    spec:
      containers:
      - name: frontend-streaming
        image: 975050024946.dkr.ecr.ca-central-1.amazonaws.com/vijaystreamingapp/frontend:v1.5  #<account-id>.dkr.ecr.<region>.amazonaws.com/shopnow/frontend:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: frontend-env 
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        # If you want to override baked-in nginx config, uncomment volumeMount and use ConfigMap below.

