apiVersion: v1
kind: Service
metadata:
  name: frontend-streaming
  namespace: vijay-streaming
  labels:
    app: frontend-streaming
spec:
  type: ClusterIP
  selector:
    app: frontend-streaming
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP

