apiVersion: v1
kind: Service
metadata:
  name: frontend-streaming-nodeport
  namespace: vijay-streaming
spec:
  type: NodePort
  selector:
    app: frontend-streaming
  ports:
  - port: 80
    targetPort: 80
   

